vich_uploader:
  db_driver: orm
  mappings:
    cvFile:
      uri_prefix:           /assets/img
      upload_destination:   '%kernel.project_dir%/public/assets/img'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer


      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true